version: "3.8"

services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: kero
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ILIkari7
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Backend/Dockerfile
    environment:
      FLASK_ENV: development
      DATABASE_URI: postgresql://postgres:ILIkari7@db:5432/kero
      LDAP_SERVER_IP: 192.168.0.61
      LDAP_BASE_DN: dc=example,dc=com
      LDAP_USERNAME: kaio
      LDAP_ADMIN_PASSWORD: ILIkari@7
      LDAP_PATH: /home/<DUMMY_USERNAME>/Desktop/users.ldif
    depends_on:
      - db
    ports:
      - "5000:5000"
    volumes:
      - ./ldif:/ldifs

  frontend:
    build:
      context: .
      dockerfile: Frontend/Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  postgres_data:
