services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: Dummy_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: DBUSER
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Backend/Dockerfile
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "5000:5000"
    restart: unless-stopped
    user: "0:0"
    volumes:
      - /root/.ssh:/root/.ssh:ro

  frontend:
    build:
      context: .
      dockerfile: Frontend/Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  postgres_data:
