version: "3.8"

services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: Dummy_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: DBUSER
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Backend/Dockerfile
    environment:
      FLASK_ENV: development
      DATABASE_URI: postgresql://postgres:DBUSER@db:5432/Dummy_db
      LDAP_SERVER_IP: openldap
      LDAP_BASE_DN: dc=example,dc=com
      LDAP_USERNAME: cn=admin,dc=example,dc=com
      LDAP_ADMIN_PASSWORD: chandan01245
      LDAP_PATH: /ldifs/users.ldif
    depends_on:
      - db
      - openldap
    ports:
      - "5000:5000"
    volumes:
      - ./ldif:/ldifs

  frontend:
    build:
      context: .
      dockerfile: Frontend/Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend

  openldap:
    image: bitnami/openldap:latest
    user: root
    container_name: openldap
    ports:
      - "389:389"
      - "636:636"
    environment:
      LDAP_ADMIN_USERNAME: admin
      LDAP_ADMIN_PASSWORD: chandan01245
      LDAP_USERS: chandan,jonathan,madhu
      LDAP_PASSWORDS: chandan01245,ILIkari7,Kickass-Password
      LDAP_ROOT: dc=example,dc=com
    volumes:
      - ./ldif:/ldifs # You can drop users.ldif here to auto-load it
      - ldap_data:/bitnami/openldap

volumes:
  postgres_data:
  ldap_data:
