services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: kero
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ILIkari7
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Backend/Dockerfile
    environment:
      FLASK_ENV: development
      DATABASE_URI: postgresql://postgres:ILIkari7@db:5432/kero
      FLASK_SECRET_KEY: change-me-in-dev
      JWT_SECRET_KEY: change-me-in-dev
    depends_on:
      - db
    ports:
      - "5000:5000"
    restart: unless-stopped
    user: "0:0"
    volumes:
      - /root/.ssh:/root/.ssh:ro

  frontend:
    build:
      context: .
      dockerfile: Frontend/Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  postgres_data:
