version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: Dummy_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: DBUSER
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Backend/Dockerfile
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://user:DBUSER@db:5432/Dummy_db
      - LDAP_SERVER_IP="192.168.1.4"
      - LDAP_USERNAME="Chandan"
      - LDAP_PASSWORD="chandan01245"
      - LDAP_PATH="/home/<DUMMY_USERNAME>/Desktop/users.ldif"

    depends_on:
      - db
    ports:
      - "5000:5000"

  frontend:
    build:
      context: .
      dockerfile: Frontend/Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data: