import {
  Box,
  Button,
  CircularProgress,
  Paper,
  TextField,
  Typography,
} from "@mui/material";
import axios, { AxiosError } from "axios";
import React, { useState } from "react";
import { useLocation, useNavigate } from "react-router-dom";
import wallpaper from "./../assets/Wallpaper.png";

function TwoFA() {
  const location = useLocation();
  const navigate = useNavigate();
  const email = (location.state as { email: string })?.email || "";
  const [code, setCode] = useState("");
  const [error, setError] = useState("");
  const [isLoading, setIsLoading] = useState(false);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError("");

    if (!code || code.length !== 6) {
      setError("Please enter a valid 6-digit code.");
      return;
    }

    setIsLoading(true);
    try {
      const token = localStorage.getItem("token");
      if (!token) {
        setError("Authentication token not found. Please log in again.");
        return;
      }

      const response = await axios.post(
        "app/verify-2fa",
        { email, code },
        {
          headers: {
            Authorization: `Bearer ${token}`,
          },
        }
      );

      if (response.data.status === "success") {
        navigate("/dashboard");
      } else {
        setError("Verification failed. Please try again.");
      }
    } catch (err) {
      const axiosError = err as AxiosError;
      console.error("2FA verification error:", axiosError.message);
      setError("An error occurred. Please try again.");
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div
      className="w-full h-screen flex items-center justify-center relative overflow-hidden"
      style={{
        backgroundImage: `url(${wallpaper})`,
        backgroundSize: "cover",
        backgroundPosition: "center",
        backgroundRepeat: "no-repeat",
        height: "100vh",
        width: "100vw",
      }}
    >
      <Box
        sx={{
          display: "flex",
          justifyContent: "center",
          alignItems: "center",
          height: "100%",
          padding: 2,
        }}
      >
        <Paper
          elevation={3}
          sx={{
            padding: 4,
            maxWidth: 400,
            width: "100%",
            textAlign: "center",
            borderRadius: 2,
            backgroundColor: "rgba(255, 255, 255, 0.9)", // Slight transparency for better readability
          }}
        >
          <Typography variant="h5" fontWeight="bold" gutterBottom>
            Two-Factor Authentication
          </Typography>
          <Typography variant="body2" color="textSecondary" gutterBottom>
            Enter the 6-digit code generated by your authenticator app.
          </Typography>
          <form onSubmit={handleSubmit}>
            <TextField
              label="6-Digit Code"
              variant="outlined"
              fullWidth
              value={code}
              onChange={(e) => setCode(e.target.value)}
              error={!!error}
              helperText={error}
              inputProps={{ maxLength: 6 }}
              sx={{ marginBottom: 2 }}
            />
            <Button
              type="submit"
              variant="contained"
              color="primary"
              fullWidth
              disabled={isLoading}
              sx={{ marginBottom: 2 }}
            >
              {isLoading ? (
                <CircularProgress size={24} color="inherit" />
              ) : (
                "Verify"
              )}
            </Button>
          </form>
          <Typography variant="body2" color="textSecondary">
            Having trouble? <a href="/help">Contact Support</a>
          </Typography>
        </Paper>
      </Box>
    </div>
  );
}

export default TwoFA;
